---
- name: creating a user
  hosts: all
  tasks: 
    - name: create a user
      user: 
        name: saiteja
        password: saiteja
        uid: 1987
        home: /home/saiteja
        shell: /bin/bash
        comment: "an average user"
...

