---
- name: implementing play scope
  hosts: all
  vars: 
    a: tomcat10
    b: present
    c: yes
  tasks: 
    - name: install/uninstall tomcat10
      apt: 
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
...          
