---
 - name: configuring tomcat10 and tomcat10-admin
   hosts: all
   tasks: 
     - name: instaling tomcat10
       apt: 
         name: tomcat10
         state: present
         update_cache: yes
     - name: installing tomcat10-admin
       apt:
         name: tomcat10-admin
         state: present
     - name: copying users.xml
       copy:
         src: tomcat-users.xml
         dest: /etc/tomcat10
     - name: chaging the port numbers
       replace: 
         regexp: 9090
         replace: 1233
         path: /etc/tomcat10/server.xml
     - name: restart tomcat10
       service: 
         name: tomcat10
         state: restarted
     - name: restarting tomcat10-admin
       service: 
         name: tomact10-admin
         state: restarted
     - name: pause for 60 seconds
       pause: 
         seconds: 60
     - name: check the response on server1
       uri: 
         url: http://172.31.7.229
         status_code: =200
     - name: check the response on server2
       uri: 
         url: http://172.31.14.37
         status_code: 200
...
